version: '3.8'

services:
  base:
    container_name: pgsql_container
    image: postgres:13.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/db_data/
    env_file:
      # - .env
      - reality_bot/.env
    ports:
      - 5432:5432
  backend:
    build:
    #image: davletelvir/neftekamsk_realty_bot_backend:latest
      
      context: .
      dockerfile: reality_bot/Dockerfile
    volumes:
      - static_value:/app/static/
    depends_on:
      - base
    env_file:
      # - .env
      - reality_bot/.env
  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/

    depends_on:
      - backend

volumes:
  static_value:
  postgres_data:
  